version: '3'

services:
  mqtt:
    image: ncarlier/mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro"
      - "./pwfile.cfg:/etc/mosquitto/pwfile.cfg:ro"
    entrypoint:
      - mosquitto
      - -c
      - /etc/mosquitto/mosquitto.conf
  ha:
    image: homeassistant/home-assistant:0.62.1
    links:
      - mqtt
    volumes:
      - './ha-config:/config'
    ports:
      - "8123:8123"
